### ISSUE TITLE
can't downlo the Datasets （for example：CCLE）

### ISSUE THREAD

**Issue by Patrickstar-flash** [bhklab/PharmacoDB#220]
CCLE <- downloadPSet(CCLE)
Error in downloadPSet(CCLE) : object 'CCLE' not found

**Comment by ChristopherEeles** [comment]
Hi @Patrickstar-flash,

It looks like you are passing a variable instead of a string to the function, add quotes around the dataset name. Also note that the string needs to match the `PSet Name` column of the table returned by `availablePSets()`, so "CCLE" needs to be "CCLE_2015".

See the documentation in `?availablePSets` and `?downloadPSet` for more information.

Best,
Christopher Eeles
Software Developer | BHK Lab | PM-Research

**Comment by Patrickstar-flash** [comment]
> 
Thanks，but I still can't download the datasets，I got this two lines R code from the 
https://pharmacodb.pmgenomics.ca/pharmacogx. 
I want to ask, if there is another way , if I download the dataset by browser, how could I put it in the pakages?
sorry, english is not good, am I clear?
